server:
  port: 8787

spring:
  datasource:
    username: myShopMall
    password: J8chd2BKcDK3sTnH
    url: jdbc:mysql://150.158.96.29:3306/myshopmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      minimum-idle: 10
    

   
#mybatis-plus配置 日志打印   

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

